### ISSUE TITLE
cmake fails at line 13 

### ISSUE THREAD

**Issue by mw0cqu** [fventuri/codecserver-mbelib-module#2]
CMake Error at CMakeLists.txt:13 (find_package):
  By not providing "FindCodecServer.cmake" in CMAKE_MODULE_PATH this project
  has asked CMake to find a package configuration file provided by
  "CodecServer", but CMake did not find one.

  Could not find a package configuration file provided by "CodecServer" with
  any of the following names:

    CodecServerConfig.cmake
    codecserver-config.cmake

  Add the installation prefix of "CodecServer" to CMAKE_PREFIX_PATH or set
  "CodecServer_DIR" to a directory containing one of the above files.  If
  "CodecServer" provides a separate development package or SDK, be sure it
  has been installed.

-- Configuring incomplete, errors occurred!

**Comment by fventuri** [comment]
@mw0cqu - as mentioned in the README here:

> Prerequisites for building this module are a successful build and install of both OpenWebRX Codec Server and mbelib. Please follow the instructions in the links provided above to build and install both dependencies.

did you first build and install OpenWebRX Codec Server as per the instructions here: https://github.com/jketterl/codecserver#compiling-from-sources ?

If you did, can you run again the step `sudo make install` when installing OpenWebRX Codec Server, and attach the output here to see if there was any error in that step?

Franco

**Comment by mw0cqu** [comment]
Good morning Franco,

Codecserver is built and functional - *implicitly* - as I was compiling your package directly having built openwebrx from the turnkey 1.1.0 image on a raspberry pi4 , before copying over my config files from my legacy 1.0.0 SD card 

mbelib also built and installed with no issue reported.

Regards

Rob

**Comment by fventuri** [comment]
Thanks Rob - I never tried to build it using the OpenWebRX Raspberry Pi image before.

I just tried to build it this morning and I had to install three additional packages here to make it work:
```
apt install libcodecserver-dev libprotobuf-dev protobuf-compiler
```

Please give it a try there and, if it works for you too, I'll add a note with that command to the README file in the repository.

Franco

**Comment by mw0cqu** [comment]
answers in stages while the information is fresh in my head / ssh window :-) 

I wiped the sd card then reinstalled the 1.1.0 image , then added the ssh file to the boot partition.
then I powered up the server. in this way, I am always starting at the same point as a newcomer

To get the above apt command to work on the pi 4 required:

**_sudo apt-get update --fix-missing
sudo apt-get update
sudo apt install libcodecserver-dev libprotobuf-dev protobuf-compiler_**

next I installed mbelib:

the method at: 

https://github.com/szechyjs/mbelib/blob/master/README.md 

works, but on the pi (when logged in as pi) the build and make commands 
after **_cd build_** all need to be prefixed with **_sudo._**

So -  additional tools in , mbelib in, lets add the codecserver plugin using your process:

Again, all the actual build commands after **_cd build_** need to be elevated with sudo on the pi build 
but once they were elevated,  it compiles first time.

as for codecserver.conf To a non-coder it is probably not clear that the extra lines required are in the source file , so as a clarification, on the pi image, go to:

**_/etc/codecserver_** 

and using nano or vi add the following lines to the existing codecserver.conf file:

**_[device:mbelib]
driver=mbelib
unvoiced_quality=3_**

then restart both the codecserver and openwebrx services 

systemctl restart codecserver
systemctl restart openwebrx

for completeness, I then tried to re-add user codecserver , but it complained the account was already created 

So - unless I have missed something this time, everything has compiled , but the extra icons are not showing 

I did a full **_sudo reboot_** , that did not bring them back either 

any thoughts ?

regards

Rob

**Comment by mw0cqu** [comment]
in the name of completeness , I also cloned the codecserver.conf file to /usr/local/etc/codecserver

restarted both services - no change

everything on the system is working (I am listening to an HF DRM broadcast on it as I type) except the digital mode menu items do not appear in the browser window

I did a **_journalctl -u opewnwebrx_** - no issues seen 

Regards

Rob

**Comment by mw0cqu** [comment]
**_Jan 17 19:07:12 openwebrx codecserver[1640]: Hello, I'm the codecserver.
Jan 17 19:07:12 openwebrx codecserver[1640]: now scanning for modules...
Jan 17 19:07:12 openwebrx codecserver[1640]: registering new driver: "ambe3k"
Jan 17 19:07:12 openwebrx codecserver[1640]: loading devices from configuration...
Jan 17 19:07:12 openwebrx codecserver[1640]: unable to load device: driver "mbelib" not available_**

I will try the mbelib build again

**Comment by mw0cqu** [comment]
tried - no change

**Comment by fventuri** [comment]
@mw0cqu - it looks like the 'codecserver' program that comes with the OpenWebRX Raspberry Pi image looks for modules only in the `/usr/lib/arm-linux-gnueabihf/codecserver` directory, while the default `sudo make install` command installs the `mbelib` module in a different directory.

To workaround this problem, please rebuild and reinstall `codecserver-mbelib-module` using the following `cmake` command instead of the one in the instructions in the README:

```
cmake -DCMAKE_INSTALL_LIBDIR='/usr/lib/arm-linux-gnueabihf' ..
```

Franco

**Comment by mw0cqu** [comment]
A job for tomorrow evening Franco! ;-) 

I will report back

**Comment by mw0cqu** [comment]
Damn! I wouldn't have slept easy anyhow....so..... out with the torch and down the garden to the shed to recover the SD card! 

And now it is working on the pi4!!

The missing element was 

**_cmake -DCMAKE_INSTALL_LIBDIR='/usr/lib/arm-linux-gnueabihf' .._**

has to be used _**twice, once during building mbelib, from scratch, once when building the codecserver-mbelib-module**_

after that **everything works** 

Many thanks Franco for your support in getting this working - great job!
